#数据库用户名
SqlUser: simple_tiktok
#数据库密码
SqlPw: 74123
#数据库地址 如 1.1.1.1:3306, hhh.com:3306
SqlAddr: cn-zz-bgp-8.natfrp.cloud:12240
Schema: simple_tiktok
#redis地址
RedisAddr: 43.143.166.162:6379
#redis密码
RedisPw: root